SET AUTOCOMMIT OFF;
COMMIT;
SET TRANSACTION NAME 'Lab6_q1';
INSERT INTO CUSTOMER VALUES (110, 'Simon', 'Garfunkel');
INSERT INTO CUSTOMER VALUES (111, 'Brian', 'McDonagh');
INSERT INTO EMPLOYEE VALUES (306, 'Lorraine', 'Keane', 304);
INSERT INTO CUST_ORDER VALUES (1026, 110, 306, 45.99);
INSERT INTO CUST_ORDER VALUES (1027, 111, 306, 34.99);
COMMIT;


----------------------------------------------

SET AUTOCOMMIT OFF;
COMMIT;
SET TRANSACTION NAME 'Lab6_q2';
INSERT INTO CUST_ORDER VALUES (1028, 110, 306, 570.80); // Don't commit here!
ROLLBACK;
COMMIT;

---------------------------------------------------

SET AUTOCOMMIT OFF;
COMMIT;
SET TRANSACTION NAME 'Lab6_q3';
INSERT INTO CUST_ORDER VALUES (1028, 110, 306, 40.99);
INSERT INTO CUST_ORDER VALUES (1029, 111, 306, 4.99);
SAVEPOINT CUST_0RDER2;
INSERT INTO CUST_ORDER VALUES (1026, 110, 306, 500.80); // Don't commit here!
ROLLBACK TO CUST_ORDER2;
COMMIT;

-------------------------------------

CONNECT sys as sysdba

CREATE USER noreen IDENTIFIED BY password;
GRANT CREATE SESSION TO noreen;
GRANT SELECT ON LAB5.EMPLOYEE TO noreen;
GRANT INSERT ON LAB5.EMPLOYEE TO noreen;
GRANT UPDATE ON LAB5.EMPLOYEE TO noreen;
GRANT DELETE ON LAB5.EMPLOYEE TO noreen;
--GRANT SELECT, INSERT, UPDATE, DELETE ON LAB5.EMPLOYEE TO noreen;
CONNECT noreen

-----------------------------------------

REVOKE DELETE ON LAB5.EMPLOYEE FROM noreen;
CONNECT noreen
DELETE FROM LAB5.EMPLOYEE WHERE EMP_ID=306;

------------------------------------------
CONNECT LAB5

SELECT FNAME, LNAME, ORDER_NBR, SALES_EMP_ID, SALES_PRICE FROM customer, CUST_ORDER 
WHERE customer.CUST_NBR=CUST_ORDER.CUST_NBR AND SALES_PRICE= (SELECT MIN(SALES_PRICE) 
FROM CUST_ORDER);

-------------------------------------------


SET AUTOCOMMIT OFF;
COMMIT;
SET TRANSACTION NAME 'Lab6_q7';
BEGIN
INSERT INTO CUST_ORDER VALUES (1030, 110, 306, 45.99);
INSERT INTO CUST_ORDER VALUES (1031, 111, 306, 34.99);
SAVEPOINT question_7;
INSERT INTO CUST_ORDER VALUES (1029, 110, 306, 570.80); // Don't commit here!
EXCEPTION WHEN DUP_VAL_ON_INDEX THEN
ROLLBACK TO SAVEPOINT_Q7;
END;
/
COMMIT;
SELECT * FROM CUST_ORDER;
------------------------------------------------------------------




